# Generated by Django 2.2.7 on 2019-11-21 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertypemodule',
            name='module_names',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_names', to='role_management.ModuleList'),
        ),
        migrations.AlterField(
            model_name='usertypemodule',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_type', to='role_management.UserType'),
        ),
    ]
