# Generated by Django 2.2.7 on 2019-11-30 10:41

from django.db import migrations, models
import project_apps.role_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('role_management', '0004_auto_20191122_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.FileField(default=1, upload_to=project_apps.role_management.models.get_upload_file_name),
            preserve_default=False,
        ),
    ]
