# Generated by Django 2.2.7 on 2019-12-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role_management', '0005_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulelist',
            name='module_url_slug',
            field=models.CharField(default=1, max_length=350, unique=True),
            preserve_default=False,
        ),
    ]
