# Generated by Django 2.2.7 on 2019-12-27 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role_management', '0007_remove_modulelist_module_url_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseManager',
        ),
    ]
