# Generated by Django 2.2.7 on 2019-12-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role_management', '0009_purchasemanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleSlug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=200, unique=True)),
                ('slug_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
