# Generated by Django 2.2.7 on 2019-12-31 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role_management', '0010_moduleslug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModuleSlug',
        ),
    ]
