# Generated by Django 2.2.7 on 2020-02-28 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role_management', '0012_loginlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginLog',
        ),
    ]
